In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
!pip install scikit-learn pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in c:\users\uttam\appdata\roaming\python\python312\site-packages (1.8.0)
Requirement already satisfied: pandas in c:\users\uttam\appdata\roaming\python\python312\site-packages (3.0.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\uttam\appdata\roaming\python\python312\site-packages (from scikit-learn) (2.4.1)
Requirement already satisfied: scipy>=1.10.0 in c:\users\uttam\appdata\roaming\python\python312\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\uttam\appdata\roaming\python\python312\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\uttam\appdata\roaming\python\python312\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\uttam\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\uttam\appdata\roaming\python\python312\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\uttam\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [24]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix

### Reading Data

In [25]:
df = pd.read_excel("C:\\Users\\uttam\\OneDrive\\Desktop\\Customer_Churn_Data_Large.xlsx")
df.head()

   CustomerID  Age Gender MaritalStatus IncomeLevel
0           1   62      M        Single         Low
1           2   65      M       Married         Low
2           3   18      M        Single         Low
3           4   21      M       Widowed         Low
4           5   21      M      Divorced      Medium

### Reading all Excel Sheet.

In [26]:
file_path = "C:\\Users\\uttam\\OneDrive\\Desktop\\Customer_Churn_Data_Large.xlsx"
fil = pd.ExcelFile(file_path)
print(fil.sheet_names)

['Customer_Demographics', 'Transaction_History', 'Customer_Service', 'Online_Activity', 'Churn_Status']

## Defining Sheets in Variable for merging.

In [27]:
df_demo = pd.read_excel("C:\\Users\\uttam\\OneDrive\\Desktop\\Customer_Churn_Data_Large.xlsx",sheet_name="Customer_Demographics")

In [28]:
df_trans = pd.read_excel("C:\\Users\\uttam\\OneDrive\\Desktop\\Customer_Churn_Data_Large.xlsx", sheet_name="Transaction_History")

In [29]:
df_service = pd.read_excel("C:\\Users\\uttam\\OneDrive\\Desktop\\Customer_Churn_Data_Large.xlsx", sheet_name = "Customer_Service")

In [30]:
df_online = pd.read_excel("C:\\Users\\uttam\\OneDrive\\Desktop\\Customer_Churn_Data_Large.xlsx", sheet_name = "Online_Activity")

In [31]:
df_churn = pd.read_excel("C:\\Users\\uttam\\OneDrive\\Desktop\\Customer_Churn_Data_Large.xlsx", sheet_name = "Churn_Status")

### Merging sheets.

In [32]:
df_merged = pd.merge(df_demo, df_trans, on = 'CustomerID')

In [33]:
df_merged = pd.merge(df_merged, df_service, on = 'CustomerID')

In [34]:
df_merged = pd.merge(df_merged, df_online, on = 'CustomerID')

In [35]:
df_finall = pd.merge(df_merged, df_churn, on = 'CustomerID')

In [38]:
df_finall.head()

,CustomerID,Age,Gender,MaritalStatus,IncomeLevel,TransactionID,TransactionDate,AmountSpent,ProductCategory,InteractionID,InteractionDate,InteractionType,ResolutionStatus,LastLoginDate,LoginFrequency,ServiceUsage,ChurnStatus
0,1,62,M,Single,Low,7194,2022-03-27,416.50,Electronics,6363,2022-03-31,Inquiry,Resolved,2023-10-21,34,Mobile App,0
1,2,65,M,Married,Low,7250,2022-08-08,54.96,Clothing,3329,2022-03-17,Inquiry,Resolved,2023-12-05,5,Website,1
2,2,65,M,Married,Low,9660,2022-07-25,197.50,Electronics,3329,2022-03-17,Inquiry,Resolved,2023-12-05,5,Website,1
3,2,65,M,Married,Low,2998,2022-01-25,101.31,Furniture,3329,2022-03-17,Inquiry,Resolved,2023-12-05,5,Website,1
4,2,65,M,Married,Low,1228,2022-07-24,397.37,Clothing,3329,2022-03-17,Inquiry,Resolved,2023-12-05,5,Website,1

## Data quality checking.

In [39]:
df_finall.isnull().sum()

CustomerID          0
Age                 0
Gender              0
MaritalStatus       0
IncomeLevel         0
TransactionID       0
TransactionDate     0
AmountSpent         0
ProductCategory     0
InteractionID       0
InteractionDate     0
InteractionType     0
ResolutionStatus    0
LastLoginDate       0
LoginFrequency      0
ServiceUsage        0
ChurnStatus         0
dtype: int64

In [41]:
df_finall.info()

<class 'pandas.DataFrame'>
RangeIndex: 5204 entries, 0 to 5203
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerID        5204 non-null   int64
 1   Age               5204 non-null   int64
 2   Gender            5204 non-null   str
 3   MaritalStatus     5204 non-null   str
 4   IncomeLevel       5204 non-null   str
 5   TransactionID     5204 non-null   int64
 6   TransactionDate   5204 non-null   datetime64[us]
 7   AmountSpent       5204 non-null   float64
 8   ProductCategory   5204 non-null   str
 9   InteractionID     5204 non-null   int64
 10  InteractionDate   5204 non-null   datetime64[us]
 11  InteractionType   5204 non-null   str
 12  ResolutionStatus  5204 non-null   str
 13  LastLoginDate     5204 non-null   datetime64[us]
 14  LoginFrequency    5204 non-null   int64
 15  ServiceUsage      5204 non-null   str
 16  ChurnStatus       5204 non-null   int64
dtypes: datetime64[us](3), float64(1), int64(6), str(7)
memory usage: 691.3 KB